select @@VERSION
create Database SalesData;
select * from sys.databases;
use SalesData;
SELECT * FROM SYS.TABLES;
--------------------------------------------------------------------------------------
SELECT * FROM [DBO].[sales_data_sample];
SELECT DISTINCT CUSTOMERNAME FROM [DBO].[sales_data_sample] ORDER BY CUSTOMERNAME;
--CHECKING UNIQUE VALUES
SELECT DISTINCT * FROM [dbo].[sales_data_sample]
SELECT DISTINCT PRODUCTLINE FROM [DBO].[sales_data_sample]
SELECT DISTINCT YEAR_ID FROM [DBO].[sales_data_sample]
SELECT DISTINCT DEALSIZE FROM [DBO].[sales_data_sample]
SELECT DISTINCT COUNTRY FROM [DBO].[sales_data_sample]
SELECT DISTINCT TERRITORY FROM [DBO].[sales_data_sample]

SELECT DISTINCT MONTH_ID FROM [DBO].[sales_data_sample]
WHERE YEAR_ID=2004
--ANALYSIS
---LEST'S START BY GROUPING SALES BY PRODUCTLINE
SELECT PRODUCTLINE,SUM(SALES) AS REVENUE FROM [dbo].[sales_data_sample] GROUP BY PRODUCTLINE ORDER BY 2 DESC;

-- LEATS START BY GROUPING SALES BY YEAR
SELECT YEAR_ID,SUM(SALES) AS REVENUE FROM [dbo].[sales_data_sample] GROUP BY YEAR_ID ;

--WHAT WAS THE BEST MONTH FOR SALES IN A SPECIFIC YEAR? HOW MUCH WAS EARNED THAT MONTH?
SELECT MONTH_ID,SUM(SALES) AS RENENUE,COUNT(ORDERNUMBER) AS FREQUENCY FROM [DBO].[sales_data_sample]
WHERE YEAR_ID=2003--CHANGE YEAR TO SEE REST
GROUP BY MONTH_ID
ORDER BY FREQUENCY DESC
 
 ---NOVEMBER SEEMS TO BE THE MONTH , WHAT PRODUCT DO THEY SELL IN NOVEMBER ,CLASSIC I BELIEVE
 SELECT MONTH_ID,PRODUCTLINE,SUM(SALES) AS RENENUE FROM [dbo].[sales_data_sample] 
 WHERE YEAR_ID=2003 AND MONTH_ID=11
 GROUP BY MONTH_ID,PRODUCTLINE
 ORDER BY RENENUE

 --WHO IS OUR BEST CUSTOMER (THIS COULD BE BEAT ANSWERES WITH RFM
 -------------RFM ANALYSIS----------------------------------------
 ---RECENCY-FREQUENCY-MONETARY(RFM)
DROP TABLE IF EXISTS #RFM
;WITH RFM AS  --WINDOW FUNCTION
(
 SELECT CUSTOMERNAME,
        SUM(SALES) AS MONETARYVALUE,
        AVG(SALES) AS AVGMONETARYVALUE,
        COUNT(ORDERNUMBER) AS FREQUENCY,
        MAX(ORDERDATE) LAST_ORDER_DATE ,
        (SELECT MAX(ORDERDATE) FROM [dbo].[sales_data_sample]) AS MAX_ODER_DATE,
        DATEDIFF(DD,MAX(ORDERDATE),(SELECT MAX(ORDERDATE) FROM [dbo].[sales_data_sample])) AS RECENCY 
 FROM [dbo].[sales_data_sample]
 GROUP BY CUSTOMERNAME
),
RFM_CAL AS 
(
	SELECT R.* ,
	  NTILE(4) OVER(ORDER BY RECENCY) AS RFM_RECENCY,
	  NTILE(4) OVER(ORDER BY FREQUENCY) AS RFM_FREQUENCY,
	  NTILE(4) OVER(ORDER BY AVGMONETARYVALUE) AS RFM_MONETARY
	FROM RFM R
	
)
SELECT C.* ,
 RFM_FREQUENCY+RFM_MONETARY+RFM_RECENCY AS RFM_CELL,
 CAST(RFM_RECENCY AS varchar)+CAST(RFM_FREQUENCY AS varchar)+CAST(RFM_MONETARY AS varchar) AS RFM_CELL_STRING
INTO #RFM
FROM RFM_CAL AS C;

SELECT CUSTOMERNAME,RFM_RECENCY,RFM_FREQUENCY,RFM_MONETARY FROM #RFM ORDER BY CUSTOMERNAME;

SELECT CUSTOMERNAME,RFM_RECENCY, RFM_FREQUENCY,RFM_MONETARY
  CASE
  WHEN RFM_
FROM #RFM




